/**
 * generated by Xtext 2.10.0
 */
package org.rslingo.rsl.rsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference DEntity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.rslingo.rsl.rsl.ReferenceDEntity#getRefDEntity <em>Ref DEntity</em>}</li>
 * </ul>
 *
 * @see org.rslingo.rsl.rsl.RslPackage#getReferenceDEntity()
 * @model
 * @generated
 */
public interface ReferenceDEntity extends EObject
{
  /**
   * Returns the value of the '<em><b>Ref DEntity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref DEntity</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref DEntity</em>' containment reference.
   * @see #setRefDEntity(RefDEntity)
   * @see org.rslingo.rsl.rsl.RslPackage#getReferenceDEntity_RefDEntity()
   * @model containment="true"
   * @generated
   */
  RefDEntity getRefDEntity();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.ReferenceDEntity#getRefDEntity <em>Ref DEntity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref DEntity</em>' containment reference.
   * @see #getRefDEntity()
   * @generated
   */
  void setRefDEntity(RefDEntity value);

} // ReferenceDEntity
