/**
 * generated by Xtext 2.10.0
 */
package org.rslingo.rsl.rsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ref UC Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.rslingo.rsl.rsl.RefUCAction#getAction <em>Action</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.RefUCAction#getNextstate <em>Nextstate</em>}</li>
 * </ul>
 *
 * @see org.rslingo.rsl.rsl.RslPackage#getRefUCAction()
 * @model
 * @generated
 */
public interface RefUCAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' reference.
   * @see #setAction(UCAction)
   * @see org.rslingo.rsl.rsl.RslPackage#getRefUCAction_Action()
   * @model
   * @generated
   */
  UCAction getAction();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.RefUCAction#getAction <em>Action</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' reference.
   * @see #getAction()
   * @generated
   */
  void setAction(UCAction value);

  /**
   * Returns the value of the '<em><b>Nextstate</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nextstate</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nextstate</em>' reference.
   * @see #setNextstate(State)
   * @see org.rslingo.rsl.rsl.RslPackage#getRefUCAction_Nextstate()
   * @model
   * @generated
   */
  State getNextstate();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.RefUCAction#getNextstate <em>Nextstate</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nextstate</em>' reference.
   * @see #getNextstate()
   * @generated
   */
  void setNextstate(State value);

} // RefUCAction
