/**
 * generated by Xtext 2.10.0
 */
package org.rslingo.rsl.rsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System Requirement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.rslingo.rsl.rsl.RslPackage#getSystemRequirement()
 * @model
 * @generated
 */
public interface SystemRequirement extends Requirement
{
} // SystemRequirement
