/**
 * generated by Xtext 2.10.0
 */
package org.rslingo.rsl.rsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Use Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getName <em>Name</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getType <em>Type</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getNameAlias <em>Name Alias</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getActorInitiates <em>Actor Initiates</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getActorParticipates <em>Actor Participates</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getDEntityView <em>DEntity View</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getPrecondition <em>Precondition</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getPostcondition <em>Postcondition</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getActions <em>Actions</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getExtensionPoints <em>Extension Points</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getIncludes <em>Includes</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getExtends <em>Extends</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getPriority <em>Priority</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getDescription <em>Description</em>}</li>
 *   <li>{@link org.rslingo.rsl.rsl.UseCase#getScenarios <em>Scenarios</em>}</li>
 * </ul>
 *
 * @see org.rslingo.rsl.rsl.RslPackage#getUseCase()
 * @model
 * @generated
 */
public interface UseCase extends SystemRequirement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.UseCase#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.rslingo.rsl.rsl.UseCaseType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.rslingo.rsl.rsl.UseCaseType
   * @see #setType(UseCaseType)
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_Type()
   * @model
   * @generated
   */
  UseCaseType getType();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.UseCase#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.rslingo.rsl.rsl.UseCaseType
   * @see #getType()
   * @generated
   */
  void setType(UseCaseType value);

  /**
   * Returns the value of the '<em><b>Name Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name Alias</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Alias</em>' attribute.
   * @see #setNameAlias(String)
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_NameAlias()
   * @model
   * @generated
   */
  String getNameAlias();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.UseCase#getNameAlias <em>Name Alias</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Alias</em>' attribute.
   * @see #getNameAlias()
   * @generated
   */
  void setNameAlias(String value);

  /**
   * Returns the value of the '<em><b>Actor Initiates</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actor Initiates</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actor Initiates</em>' reference.
   * @see #setActorInitiates(Actor)
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_ActorInitiates()
   * @model
   * @generated
   */
  Actor getActorInitiates();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.UseCase#getActorInitiates <em>Actor Initiates</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actor Initiates</em>' reference.
   * @see #getActorInitiates()
   * @generated
   */
  void setActorInitiates(Actor value);

  /**
   * Returns the value of the '<em><b>Actor Participates</b></em>' containment reference list.
   * The list contents are of type {@link org.rslingo.rsl.rsl.RefActor}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actor Participates</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actor Participates</em>' containment reference list.
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_ActorParticipates()
   * @model containment="true"
   * @generated
   */
  EList<RefActor> getActorParticipates();

  /**
   * Returns the value of the '<em><b>DEntity View</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>DEntity View</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>DEntity View</em>' reference.
   * @see #setDEntityView(DataEntityView)
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_DEntityView()
   * @model
   * @generated
   */
  DataEntityView getDEntityView();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.UseCase#getDEntityView <em>DEntity View</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>DEntity View</em>' reference.
   * @see #getDEntityView()
   * @generated
   */
  void setDEntityView(DataEntityView value);

  /**
   * Returns the value of the '<em><b>Precondition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Precondition</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precondition</em>' attribute.
   * @see #setPrecondition(String)
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_Precondition()
   * @model
   * @generated
   */
  String getPrecondition();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.UseCase#getPrecondition <em>Precondition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precondition</em>' attribute.
   * @see #getPrecondition()
   * @generated
   */
  void setPrecondition(String value);

  /**
   * Returns the value of the '<em><b>Postcondition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Postcondition</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Postcondition</em>' attribute.
   * @see #setPostcondition(String)
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_Postcondition()
   * @model
   * @generated
   */
  String getPostcondition();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.UseCase#getPostcondition <em>Postcondition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Postcondition</em>' attribute.
   * @see #getPostcondition()
   * @generated
   */
  void setPostcondition(String value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actions</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference.
   * @see #setActions(UCActions)
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_Actions()
   * @model containment="true"
   * @generated
   */
  UCActions getActions();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.UseCase#getActions <em>Actions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actions</em>' containment reference.
   * @see #getActions()
   * @generated
   */
  void setActions(UCActions value);

  /**
   * Returns the value of the '<em><b>Extension Points</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Extension Points</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extension Points</em>' containment reference.
   * @see #setExtensionPoints(UCExtensionPoints)
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_ExtensionPoints()
   * @model containment="true"
   * @generated
   */
  UCExtensionPoints getExtensionPoints();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.UseCase#getExtensionPoints <em>Extension Points</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extension Points</em>' containment reference.
   * @see #getExtensionPoints()
   * @generated
   */
  void setExtensionPoints(UCExtensionPoints value);

  /**
   * Returns the value of the '<em><b>Includes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Includes</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Includes</em>' containment reference.
   * @see #setIncludes(UCIncludes)
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_Includes()
   * @model containment="true"
   * @generated
   */
  UCIncludes getIncludes();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.UseCase#getIncludes <em>Includes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Includes</em>' containment reference.
   * @see #getIncludes()
   * @generated
   */
  void setIncludes(UCIncludes value);

  /**
   * Returns the value of the '<em><b>Extends</b></em>' containment reference list.
   * The list contents are of type {@link org.rslingo.rsl.rsl.UCExtends}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Extends</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extends</em>' containment reference list.
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_Extends()
   * @model containment="true"
   * @generated
   */
  EList<UCExtends> getExtends();

  /**
   * Returns the value of the '<em><b>Priority</b></em>' attribute.
   * The literals are from the enumeration {@link org.rslingo.rsl.rsl.PriorityType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Priority</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priority</em>' attribute.
   * @see org.rslingo.rsl.rsl.PriorityType
   * @see #setPriority(PriorityType)
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_Priority()
   * @model
   * @generated
   */
  PriorityType getPriority();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.UseCase#getPriority <em>Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Priority</em>' attribute.
   * @see org.rslingo.rsl.rsl.PriorityType
   * @see #getPriority()
   * @generated
   */
  void setPriority(PriorityType value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.rslingo.rsl.rsl.UseCase#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Scenarios</b></em>' containment reference list.
   * The list contents are of type {@link org.rslingo.rsl.rsl.Scenario}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scenarios</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenarios</em>' containment reference list.
   * @see org.rslingo.rsl.rsl.RslPackage#getUseCase_Scenarios()
   * @model containment="true"
   * @generated
   */
  EList<Scenario> getScenarios();

} // UseCase
