/*
 * generated by Xtext 2.10.0
 */
package org.rslingo.rsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/rslingo/rsl/parser/antlr/internal/InternalRsl.tokens");
	}
}
