/*
 * generated by Xtext 2.10.0
 */
package org.rslingo.rsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.rslingo.rsl.parser.antlr.internal.InternalRslParser;
import org.rslingo.rsl.services.RslGrammarAccess;

public class RslParser extends AbstractAntlrParser {

	@Inject
	private RslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRslParser createParser(XtextTokenStream stream) {
		return new InternalRslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
