/**
 * generated by Xtext 2.10.0
 */
package org.rslingo.rsl.rsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.rslingo.rsl.rsl.DataEntity;
import org.rslingo.rsl.rsl.MasterDEntity;
import org.rslingo.rsl.rsl.RslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Master DEntity</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.rslingo.rsl.rsl.impl.MasterDEntityImpl#getMasterDEntity <em>Master DEntity</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MasterDEntityImpl extends MinimalEObjectImpl.Container implements MasterDEntity
{
  /**
   * The cached value of the '{@link #getMasterDEntity() <em>Master DEntity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMasterDEntity()
   * @generated
   * @ordered
   */
  protected DataEntity masterDEntity;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MasterDEntityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RslPackage.Literals.MASTER_DENTITY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataEntity getMasterDEntity()
  {
    if (masterDEntity != null && masterDEntity.eIsProxy())
    {
      InternalEObject oldMasterDEntity = (InternalEObject)masterDEntity;
      masterDEntity = (DataEntity)eResolveProxy(oldMasterDEntity);
      if (masterDEntity != oldMasterDEntity)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RslPackage.MASTER_DENTITY__MASTER_DENTITY, oldMasterDEntity, masterDEntity));
      }
    }
    return masterDEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataEntity basicGetMasterDEntity()
  {
    return masterDEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMasterDEntity(DataEntity newMasterDEntity)
  {
    DataEntity oldMasterDEntity = masterDEntity;
    masterDEntity = newMasterDEntity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RslPackage.MASTER_DENTITY__MASTER_DENTITY, oldMasterDEntity, masterDEntity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RslPackage.MASTER_DENTITY__MASTER_DENTITY:
        if (resolve) return getMasterDEntity();
        return basicGetMasterDEntity();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RslPackage.MASTER_DENTITY__MASTER_DENTITY:
        setMasterDEntity((DataEntity)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RslPackage.MASTER_DENTITY__MASTER_DENTITY:
        setMasterDEntity((DataEntity)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RslPackage.MASTER_DENTITY__MASTER_DENTITY:
        return masterDEntity != null;
    }
    return super.eIsSet(featureID);
  }

} //MasterDEntityImpl
