/**
 * generated by Xtext 2.10.0
 */
package org.rslingo.rsl.rsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.rslingo.rsl.rsl.RefDEntity;
import org.rslingo.rsl.rsl.ReferenceDEntity;
import org.rslingo.rsl.rsl.RslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Reference DEntity</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.rslingo.rsl.rsl.impl.ReferenceDEntityImpl#getRefDEntity <em>Ref DEntity</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReferenceDEntityImpl extends MinimalEObjectImpl.Container implements ReferenceDEntity
{
  /**
   * The cached value of the '{@link #getRefDEntity() <em>Ref DEntity</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefDEntity()
   * @generated
   * @ordered
   */
  protected RefDEntity refDEntity;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReferenceDEntityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RslPackage.Literals.REFERENCE_DENTITY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RefDEntity getRefDEntity()
  {
    return refDEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRefDEntity(RefDEntity newRefDEntity, NotificationChain msgs)
  {
    RefDEntity oldRefDEntity = refDEntity;
    refDEntity = newRefDEntity;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RslPackage.REFERENCE_DENTITY__REF_DENTITY, oldRefDEntity, newRefDEntity);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRefDEntity(RefDEntity newRefDEntity)
  {
    if (newRefDEntity != refDEntity)
    {
      NotificationChain msgs = null;
      if (refDEntity != null)
        msgs = ((InternalEObject)refDEntity).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RslPackage.REFERENCE_DENTITY__REF_DENTITY, null, msgs);
      if (newRefDEntity != null)
        msgs = ((InternalEObject)newRefDEntity).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RslPackage.REFERENCE_DENTITY__REF_DENTITY, null, msgs);
      msgs = basicSetRefDEntity(newRefDEntity, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RslPackage.REFERENCE_DENTITY__REF_DENTITY, newRefDEntity, newRefDEntity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RslPackage.REFERENCE_DENTITY__REF_DENTITY:
        return basicSetRefDEntity(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RslPackage.REFERENCE_DENTITY__REF_DENTITY:
        return getRefDEntity();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RslPackage.REFERENCE_DENTITY__REF_DENTITY:
        setRefDEntity((RefDEntity)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RslPackage.REFERENCE_DENTITY__REF_DENTITY:
        setRefDEntity((RefDEntity)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RslPackage.REFERENCE_DENTITY__REF_DENTITY:
        return refDEntity != null;
    }
    return super.eIsSet(featureID);
  }

} //ReferenceDEntityImpl
