/**
 * generated by Xtext 2.10.0
 */
package org.rslingo.rsl.rsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.rslingo.rsl.rsl.RslPackage;
import org.rslingo.rsl.rsl.SystemRequirement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>System Requirement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SystemRequirementImpl extends RequirementImpl implements SystemRequirement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SystemRequirementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RslPackage.Literals.SYSTEM_REQUIREMENT;
  }

} //SystemRequirementImpl
